using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace OneShot.Generator;

internal static class Emitter
{
    public static string Emit(TypeModel model)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();

        var className = "OneShot_TypeInfo_" + model.SafeName;

        // TypeInfo class
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine(string.Format("internal sealed class {0} : global::OneShot.ITypeInfo", className));
        sb.AppendLine("{");
        sb.AppendLine(string.Format("    public static readonly {0} Instance = new {0}();", className));
        sb.AppendLine();
        sb.AppendLine(string.Format("    public global::System.Type ConcreteType => typeof({0});", model.FullyQualifiedName));
        sb.AppendLine();

        EmitCreate(sb, model);
        sb.AppendLine();
        EmitInjectAll(sb, model);
        sb.AppendLine();
        EmitTypeArrayProperty(sb, "Interfaces", model.Interfaces);
        sb.AppendLine();
        EmitTypeArrayProperty(sb, "BaseTypes", model.BaseTypes);
        EmitUnsafeAccessors(sb, model);
        sb.AppendLine("}");
        sb.AppendLine();

        // Module initializer
        sb.AppendLine("internal static partial class OneShotModuleInit");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine(string.Format("    internal static void Register_{0}()", model.SafeName));
        sb.AppendLine("    {");
        sb.AppendLine(string.Format("        global::OneShot.TypeInfoRegistry.Register({0}.Instance);", className));
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitCreate(StringBuilder sb, TypeModel model)
    {
        sb.AppendLine("    public object Create(global::OneShot.Container container)");
        sb.AppendLine("    {");

        if (!model.Constructor.HasValue)
        {
            sb.AppendLine(string.Format(
                "        throw new global::System.NotSupportedException(\"No suitable constructor found for {0}. Mark one with [Inject].\");",
                model.FullyQualifiedName));
        }
        else if (model.Constructor.Value.Parameters.Length == 0)
        {
            sb.AppendLine(string.Format("        return new {0}();", model.FullyQualifiedName));
        }
        else
        {
            var parameters = model.Constructor.Value.Parameters;
            for (int i = 0; i < parameters.Length; i++)
                EmitResolveParam(sb, i, parameters[i], "");

            var args = string.Join(", ", Enumerable.Range(0, parameters.Length).Select(i => string.Format("__p{0}", i)));
            sb.AppendLine(string.Format("        return new {0}({1});", model.FullyQualifiedName, args));
        }

        sb.AppendLine("    }");
    }

    private static void EmitResolveParam(StringBuilder sb, int index, ParameterModel p, string prefix)
    {
        var v = string.Format("__{0}p{1}", prefix, index);

        if (p.HasDefault)
        {
            var label = p.LabelFqn != null
                ? string.Format("typeof({0})", p.LabelFqn)
                : "null";
            sb.AppendLine(string.Format("        var {0}_r = container.TryResolve(typeof({1}), {2});", v, p.TypeFqn, label));
            sb.AppendLine(string.Format("        var {0} = {0}_r != null ? ({1}){0}_r : {2};", v, p.TypeFqn, p.DefaultExpr));
        }
        else
        {
            if (p.LabelFqn != null)
                sb.AppendLine(string.Format("        var {0} = container.Resolve<{1}>(typeof({2}));", v, p.TypeFqn, p.LabelFqn));
            else
                sb.AppendLine(string.Format("        var {0} = container.Resolve<{1}>();", v, p.TypeFqn));
        }
    }

    private static void EmitInjectAll(StringBuilder sb, TypeModel model)
    {
        sb.AppendLine("    public void InjectAll(global::OneShot.Container container, object instance)");
        sb.AppendLine("    {");

        bool hasAny = model.Fields.Length > 0 || model.Properties.Length > 0 || model.Methods.Length > 0;
        if (!hasAny)
        {
            sb.AppendLine("    }");
            return;
        }

        sb.AppendLine(string.Format("        var target = ({0})instance;", model.FullyQualifiedName));

        // Fields
        foreach (var field in model.Fields)
        {
            var resolve = ResolveExpr(field.TypeFqn, field.LabelFqn);
            if (field.NeedsUnsafeAccessor)
                sb.AppendLine(string.Format("        UnsafeGet_{0}(target) = {1};", SanitizeName(field.Name), resolve));
            else
                sb.AppendLine(string.Format("        target.{0} = {1};", field.Name, resolve));
        }

        // Properties
        foreach (var prop in model.Properties)
        {
            var resolve = ResolveExpr(prop.TypeFqn, prop.LabelFqn);
            if (prop.NeedsUnsafeAccessor)
                sb.AppendLine(string.Format("        UnsafeSet_{0}(target, {1});", prop.Name, resolve));
            else
                sb.AppendLine(string.Format("        target.{0} = {1};", prop.Name, resolve));
        }

        // Methods
        for (int mi = 0; mi < model.Methods.Length; mi++)
        {
            var method = model.Methods[mi];
            for (int pi = 0; pi < method.Parameters.Length; pi++)
                EmitResolveParam(sb, pi, method.Parameters[pi], string.Format("m{0}_", mi));

            var args = string.Join(", ", Enumerable.Range(0, method.Parameters.Length)
                .Select(i => string.Format("__m{0}_p{1}", mi, i)));

            if (method.NeedsUnsafeAccessor)
            {
                var callArgs = method.Parameters.Length > 0
                    ? string.Format("target, {0}", args) : "target";
                sb.AppendLine(string.Format("        UnsafeCall_{0}_{1}({2});", mi, method.Name, callArgs));
            }
            else
            {
                sb.AppendLine(string.Format("        target.{0}({1});", method.Name, args));
            }
        }

        sb.AppendLine("    }");
    }

    private static string ResolveExpr(string typeFqn, string? labelFqn)
    {
        return labelFqn != null
            ? string.Format("container.Resolve<{0}>(typeof({1}))", typeFqn, labelFqn)
            : string.Format("container.Resolve<{0}>()", typeFqn);
    }

    private static void EmitTypeArrayProperty(StringBuilder sb, string name, ImmutableArray<string> types)
    {
        if (types.Length == 0)
        {
            sb.AppendLine(string.Format(
                "    public global::System.Collections.Generic.IReadOnlyList<global::System.Type> {0} {{ get; }} = global::System.Array.Empty<global::System.Type>();",
                name));
        }
        else
        {
            var items = string.Join(", ", types.Select(t => string.Format("typeof({0})", t)));
            sb.AppendLine(string.Format(
                "    public global::System.Collections.Generic.IReadOnlyList<global::System.Type> {0} {{ get; }} = new global::System.Type[] {{ {1} }};",
                name, items));
        }
    }

    private static void EmitUnsafeAccessors(StringBuilder sb, TypeModel model)
    {
        var typeName = model.FullyQualifiedName;
        var targetParam = model.IsValueType
            ? string.Format("ref {0}", typeName) : typeName;

        // Field accessors
        foreach (var field in model.Fields)
        {
            if (!field.NeedsUnsafeAccessor) continue;
            var accessor = SanitizeName(field.Name);
            sb.AppendLine();
            sb.AppendLine(string.Format(
                "    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = \"{0}\")]",
                field.Name));
            sb.AppendLine(string.Format(
                "    private static extern ref {0} UnsafeGet_{1}({2} target);",
                field.TypeFqn, accessor, targetParam));
        }

        // Property setter accessors
        foreach (var prop in model.Properties)
        {
            if (!prop.NeedsUnsafeAccessor) continue;
            sb.AppendLine();
            sb.AppendLine(string.Format(
                "    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"set_{0}\")]",
                prop.Name));
            sb.AppendLine(string.Format(
                "    private static extern void UnsafeSet_{0}({1} target, {2} value);",
                prop.Name, targetParam, prop.TypeFqn));
        }

        // Method accessors
        for (int mi = 0; mi < model.Methods.Length; mi++)
        {
            var method = model.Methods[mi];
            if (!method.NeedsUnsafeAccessor) continue;

            var methodParams = string.Join(", ",
                new[] { string.Format("{0} target", targetParam) }
                .Concat(method.Parameters.Select((p, i) =>
                    string.Format("{0} __p{1}", p.TypeFqn, i))));

            sb.AppendLine();
            sb.AppendLine(string.Format(
                "    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"{0}\")]",
                method.Name));
            sb.AppendLine(string.Format(
                "    private static extern {0} UnsafeCall_{1}_{2}({3});",
                method.ReturnTypeFqn, mi, method.Name, methodParams));
        }
    }

    private static string SanitizeName(string name)
    {
        return name.Replace('<', '_').Replace('>', '_');
    }
}
