name: dotnet-unit-test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.306 # https://github.com/microsoft/testfx/issues/1733
    - name: Build and Test
      run: |
        cd .NET
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal