name: publish-nuget-package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Standard
    - name: Pack
      run: |
        cd Standard/OneShotInjection
        dotnet pack -c Release -o out
    - name: Publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./Standard/OneShotInjection/out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
