name: unity-test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - Mono2x
          - IL2CPP
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            Library
            CodeCoverage
          key: LibraryAndCoverage
      - uses: game-ci/unity-test-runner@v2
        id: unity-test
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          customParameters: -scriptingBackend ${{ matrix.backend }} -testCategory "!benchmark"
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;pathFilters:+**/Packages/**'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results for ${{ matrix.backend }}
          path: ${{ steps.unity-test.outputs.coveragePath }}
